/**
 * GroupDetailModal
 * Extracted from GroupsContent.tsx during Phase 1.2
 * Shows group details, member list, and join/leave/chat actions.
 * Rendered via createPortal to escape stacking context.
 */
import React, { useEffect, useState, useRef, useCallback } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { createPortal } from 'react-dom';
import {
    groupCategoryConfig,
    getRoleInfo,
    formatLastActive,
    type GroupWithMembers,
} from '../../../../../services/groupsService';
import { getProfile, getImages } from '../../../../../services/profileService';
import { getCurrentLevel, getXPProgress } from '../../../../../services/studyTimeService';
import GroupIcon from '../components/GroupIcon';
import {
    Carousel,
    CarouselContent,
    CarouselItem,
} from '../../../../../components/ui/carousel';
import { AnimatedCircularProgressBar } from '../../../../../components/ui/animated-circular-progress-bar';

interface GroupDetailModalProps {
    group: GroupWithMembers | null;
    isOpen: boolean;
    onClose: () => void;
    onJoin: (groupId: string) => void;
    onLeave: (groupId: string) => void;
}

const GroupDetailModal: React.FC<GroupDetailModalProps> = ({
    group, isOpen, onClose, onJoin, onLeave
}) => {
    const [isDarkMode, setIsDarkMode] = useState(() => document.body.classList.contains('dark-mode') || document.documentElement.classList.contains("dark"));
    
    const myProfile = getProfile();
    const myImages = getImages();
    const myLevel = getCurrentLevel();
    const myProgress = getXPProgress();

    // Auto-minimizing header state - initialized to false for both PC/Desktop and Mobile/Tablet
    const [isMinimized, setIsMinimized] = useState(false);
    const lastScrollY = useRef(0);
    const scrollDirection = useRef<'up' | 'down' | null>(null);
    const anchorScrollY = useRef(0);

    // Pagination for Teacher's Resources
    const [currentResourcePage, setCurrentResourcePage] = useState(0);

    const [downloadProgress, setDownloadProgress] = useState<Record<number, number>>({});
    const [completedResources, setCompletedResources] = useState<number[]>([]);

    const handleDownloadResource = (e: React.MouseEvent, resource: any) => {
        e.stopPropagation();
        const id = resource.id;
        if (downloadProgress[id] !== undefined || completedResources.includes(id)) return;

        setDownloadProgress(prev => ({ ...prev, [id]: 0 }));

        let currentProgress = 0;
        const interval = setInterval(() => {
            // Realistic jumping progress
            const jump = Math.floor(Math.random() * 25) + 8;
            currentProgress += jump;
            
            if (currentProgress >= 100) {
                currentProgress = 100;
                clearInterval(interval);
                
                // Wait for progress bar animation to finish before turning to checkmark and triggering download
                setTimeout(() => {
                    // Trigger a real browser file download using Blob for realism!
                    try {
                        const content = `[DATABASE MOCK]\nFile: ${resource.name}\nSize: ${resource.size}\nType: ${resource.type}\n\nThis is a real mock file generated by the client so the download flow actually works! In the future, this will connect directly to the teacher's uploaded PDF URL.`;
                        const blob = new Blob([content], { type: 'text/plain' });
                        const url = URL.createObjectURL(blob);
                        const a = document.createElement('a');
                        a.href = url;
                        a.download = resource.name;
                        document.body.appendChild(a);
                        a.click();
                        document.body.removeChild(a);
                        URL.revokeObjectURL(url);
                    } catch(err) {
                        console.error("Download trigger failed:", err);
                    }

                    setDownloadProgress(prev => {
                        const newProgress = { ...prev };
                        delete newProgress[id];
                        return newProgress;
                    });
                    setCompletedResources(prev => [...prev, id]);
                }, 500);
            } else {
                setDownloadProgress(prev => ({ ...prev, [id]: currentProgress }));
            }
        }, 400);
    };
    
    // Dummy resources to demonstrate pagination
    const allResources = [
        { id: 1, name: 'Project_Requirements.pdf', type: 'Syllabus', size: '2.4 MB' },
        { id: 2, name: 'Rubrics_Grading.pdf', type: 'Guide', size: '1.1 MB' },
        { id: 3, name: 'Sample_Prototype.zip', type: 'Example', size: '15 MB' },
        { id: 4, name: 'Lecture_Slides_W1.pdf', type: 'Slides', size: '4.2 MB' },
        { id: 5, name: 'API_Documentation.pdf', type: 'Reference', size: '3.8 MB' },
    ];
    
    const resourcesPerPage = 2;
    const totalResourcePages = Math.ceil(allResources.length / resourcesPerPage);
    
    // Group resources into pages for the Carousel
    const resourcePages = [];
    for (let i = 0; i < allResources.length; i += resourcesPerPage) {
        resourcePages.push(allResources.slice(i, i + resourcesPerPage));
    }

    const handleScroll = useCallback((e: React.UIEvent<HTMLDivElement>) => {
        const currentScrollY = e.currentTarget.scrollTop;
        
        // Handle iOS rubber banding / top of scroll
        if (currentScrollY <= 10) {
            setIsMinimized(false);
            lastScrollY.current = currentScrollY;
            scrollDirection.current = null;
            anchorScrollY.current = currentScrollY;
            return;
        }

        const delta = currentScrollY - lastScrollY.current;
        
        if (delta > 0) {
            if (scrollDirection.current !== 'down') {
                scrollDirection.current = 'down';
                anchorScrollY.current = lastScrollY.current;
            }
            if (currentScrollY - anchorScrollY.current > 30) {
                setIsMinimized(true);
            }
        } else if (delta < 0) {
            if (scrollDirection.current !== 'up') {
                scrollDirection.current = 'up';
                anchorScrollY.current = lastScrollY.current;
            }
            // Do not expand just by scrolling up. Only expand at the very top.
        }

        lastScrollY.current = currentScrollY;
    }, []);

    useEffect(() => {
        const checkDarkMode = () => setIsDarkMode(document.body.classList.contains('dark-mode') || document.documentElement.classList.contains("dark"));
        const observer = new MutationObserver(checkDarkMode);
        observer.observe(document.body, { attributes: true, attributeFilter: ['class'] });
        observer.observe(document.documentElement, { attributes: true, attributeFilter: ['class'] });
        return () => observer.disconnect();
    }, []);

    useEffect(() => {
        const handleKeyDown = (e: KeyboardEvent) => {
            if (e.key === 'Escape' && isOpen) onClose();
        };
        document.addEventListener('keydown', handleKeyDown);
        return () => document.removeEventListener('keydown', handleKeyDown);
    }, [isOpen, onClose]);

    useEffect(() => {
        if (isOpen) {
            document.body.style.overflow = 'hidden';
            setIsMinimized(false);
        }
        else document.body.style.overflow = '';
        return () => { document.body.style.overflow = ''; };
    }, [isOpen]);

    if (!group) return null;

    const categoryConfig = groupCategoryConfig[group.category];

    return createPortal(
        <AnimatePresence>
            {isOpen && (
                <div className="fixed inset-0 z-[99998] flex items-center justify-center p-0 sm:p-5">
                    {/* Backdrop */}
                    <motion.div
                        initial={{ opacity: 0 }}
                        animate={{ opacity: 1 }}
                        exit={{ opacity: 0 }}
                        onClick={onClose}
                        className="absolute inset-0 bg-black/60 dark:bg-black/80 backdrop-blur-md"
                    />

                    {/* Modal */}
                    <motion.div
                        layout
                        initial={{ opacity: 0, scale: 0.95, y: 20 }}
                        animate={{ opacity: 1, scale: 1, y: 0 }}
                        exit={{ opacity: 0, scale: 0.95, y: 20 }}
                        transition={{ 
                            type: 'spring', 
                            damping: 28, 
                            stiffness: 350,
                            layout: { type: 'spring', damping: 25, stiffness: 200 }
                        }}
                        className="relative w-full max-w-[540px] md:max-w-[800px] lg:max-w-[850px] h-[100dvh] sm:h-[85vh] sm:max-h-[800px] bg-slate-50 dark:bg-slate-900 rounded-none sm:rounded-[20px] shadow-2xl overflow-hidden flex flex-col"
                        onClick={(e) => e.stopPropagation()}
                    >
                        {/* Header Container */}
                        <motion.div 
                            animate={{
                                padding: isMinimized ? '12px 16px' : '16px 20px 8px 20px'
                            }}
                            className="relative border-b border-zinc-100 dark:border-zinc-800/50 bg-zinc-50/50 dark:bg-zinc-900/50 rounded-none sm:rounded-t-[20px]"
                        >
                            <motion.div 
                                animate={{ marginBottom: isMinimized ? '0px' : '16px' }}
                                className="flex items-start gap-3 sm:gap-4"
                            >
                                {/* Header Card */}
                                <motion.div 
                                    initial={{ opacity: 0, y: -10 }}
                                    animate={{ 
                                        opacity: 1, 
                                        y: 0,
                                        padding: isMinimized ? '12px 16px' : '16px 20px',
                                        gap: isMinimized ? '16px' : '20px'
                                    }}
                                    transition={{ type: 'spring', stiffness: 300, damping: 24, delay: 0.1 }}
                                    className="flex-1 relative overflow-hidden bg-white dark:bg-zinc-900 border border-zinc-200/80 dark:border-zinc-800/80 shadow-sm rounded-[20px] sm:rounded-[24px] flex items-start group transition-all duration-300 hover:shadow-md text-left"
                                    style={{
                                        borderColor: isDarkMode ? '#27272a' : '#e4e4e7',
                                    }}
                                >
                                    {/* SaaS Background Accents matching the group color */}
                                    <div 
                                        className="absolute top-0 right-0 -mr-16 -mt-16 w-48 h-48 rounded-full blur-3xl pointer-events-none transition-transform duration-700 group-hover:scale-150" 
                                        style={{ background: `${group.color}15` }} 
                                        aria-hidden="true" 
                                    />
                                    <div 
                                        className="absolute bottom-0 left-0 -ml-16 -mb-16 w-32 h-32 rounded-full blur-3xl pointer-events-none transition-transform duration-700 group-hover:scale-150" 
                                        style={{ background: `${group.color}10` }} 
                                        aria-hidden="true" 
                                    />

                                    <div className="relative overflow-visible flex-shrink-0">
                                    {/* Mobile Icon */}
                                    <motion.div
                                        animate={{
                                            width: isMinimized ? 40 : 48,
                                            height: isMinimized ? 40 : 48,
                                            borderRadius: isMinimized ? 12 : 14
                                        }}
                                        whileHover={{ scale: 1.05, rotate: -5 }}
                                        transition={{ type: 'spring', stiffness: 400, damping: 15 }}
                                        className={`flex sm:hidden items-center justify-center flex-shrink-0 relative z-10 ${
                                            group.is_pinned 
                                                ? 'ring-[2.5px] ring-amber-400 dark:ring-amber-500' 
                                                : 'shadow-sm'
                                        }`}
                                        style={{
                                            background: `linear-gradient(135deg, ${categoryConfig.color}15, ${categoryConfig.color}05)`,
                                            border: group.is_pinned ? 'none' : `1px solid ${categoryConfig.color}20`,
                                            color: categoryConfig.color
                                        }}
                                    >
                                        {group.is_pinned && (
                                            <div className="absolute -top-1.5 -right-1.5 w-[18px] h-[18px] bg-amber-100 dark:bg-amber-900 rounded-full border border-amber-200 dark:border-amber-700 flex items-center justify-center shadow-md z-10 text-amber-500 dark:text-amber-400">
                                                <svg width="10" height="10" viewBox="0 0 24 24" fill="currentColor" stroke="currentColor" strokeWidth="2">
                                                    <path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z" />
                                                </svg>
                                            </div>
                                        )}
                                        <svg 
                                            width={isMinimized ? 18 : 20} 
                                            height={isMinimized ? 18 : 20} 
                                            viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"
                                            className="transition-all duration-300"
                                        >
                                            <path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M23 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path>
                                        </svg>
                                    </motion.div>

                                    {/* Desktop Icon */}
                                    <motion.div
                                        animate={{
                                            width: isMinimized ? 44 : 52,
                                            height: isMinimized ? 44 : 52,
                                            borderRadius: isMinimized ? 12 : 16
                                        }}
                                        whileHover={{ scale: 1.05, rotate: -5 }}
                                        transition={{ type: 'spring', stiffness: 400, damping: 15 }}
                                        className={`hidden sm:flex items-center justify-center flex-shrink-0 relative z-10 ${
                                            group.is_pinned 
                                                ? 'ring-[2.5px] ring-amber-400 dark:ring-amber-500' 
                                                : 'shadow-sm'
                                        }`}
                                        style={{
                                            background: `linear-gradient(135deg, ${categoryConfig.color}15, ${categoryConfig.color}05)`,
                                            border: group.is_pinned ? 'none' : `1px solid ${categoryConfig.color}20`,
                                            color: categoryConfig.color
                                        }}
                                    >
                                        {group.is_pinned && (
                                            <div className="absolute -top-2 -right-2 w-[22px] h-[22px] bg-amber-100 dark:bg-amber-900 rounded-full border border-amber-200 dark:border-amber-700 flex items-center justify-center shadow-md z-10 text-amber-500 dark:text-amber-400">
                                                <svg width="12" height="12" viewBox="0 0 24 24" fill="currentColor" stroke="currentColor" strokeWidth="2">
                                                    <path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z" />
                                                </svg>
                                            </div>
                                        )}
                                        
                                        {group.avatar ? (
                                            <img src={group.avatar} alt={group.name} className="w-full h-full object-cover rounded-[inherit]" />
                                        ) : (
                                            <GroupIcon icon={group.icon} color={group.color} size={isMinimized ? 20 : 26} />
                                        )}
                                    </motion.div>
                                    </div>
                                
                                {/* Info Area */}
                                <div className="relative z-10 flex-1 min-w-0 pr-2">
                                    <div className="flex items-center mb-0.5">
                                        {/* Mobile Title */}
                                        <motion.h2 
                                            animate={{ fontSize: isMinimized ? '16px' : '18px' }}
                                            className="font-bold text-slate-800 dark:text-slate-100 tracking-tight m-0 truncate sm:hidden"
                                        >
                                            {group.name}
                                        </motion.h2>
                                        
                                        {/* Desktop Title */}
                                        <motion.h2 
                                            animate={{ fontSize: isMinimized ? '16px' : '22px' }}
                                            className="font-bold text-slate-800 dark:text-slate-100 tracking-tight m-0 truncate hidden sm:block"
                                        >
                                            {group.name}
                                        </motion.h2>
                                    </div>
                                    
                                    <AnimatePresence initial={false}>
                                        {!isMinimized ? (
                                            <motion.div
                                                initial={{ height: 0, opacity: 0 }}
                                                animate={{ height: 'auto', opacity: 1 }}
                                                exit={{ height: 0, opacity: 0 }}
                                                transition={{ duration: 0.2 }}
                                                className="overflow-hidden"
                                            >
                                                <p className="text-xs sm:text-[12px] text-slate-500 dark:text-slate-400 m-0 mb-1.5 sm:mb-2 leading-snug sm:leading-relaxed line-clamp-2">
                                                    {group.description}
                                                </p>
                                                <div className="flex gap-2 flex-wrap">
                                                    {group.course_name && (
                                                        <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-lg text-[11px] font-bold tracking-wide bg-purple-100 text-purple-600 dark:bg-purple-900/30 dark:text-purple-400">
                                                            <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                                                                <path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20" />
                                                                <path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z" />
                                                            </svg>
                                                            {group.course_name}
                                                        </span>
                                                    )}
                                                    {group.is_private && (
                                                        <span className="px-2.5 py-1 rounded-full text-[11px] font-bold tracking-wide bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-400 flex items-center gap-1">
                                                            <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5"><rect x="3" y="11" width="18" height="11" rx="2" ry="2" /><path d="M7 11V7a5 5 0 0 1 10 0v4" /></svg>
                                                            Private
                                                        </span>
                                                    )}
                                                </div>
                                            </motion.div>
                                        ) : (
                                            <motion.div
                                                initial={{ height: 0, opacity: 0 }}
                                                animate={{ height: 'auto', opacity: 1 }}
                                                exit={{ height: 0, opacity: 0 }}
                                                transition={{ duration: 0.2 }}
                                                className="overflow-hidden flex items-center gap-2 flex-wrap"
                                            >
                                                {group.course_name && (
                                                    <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-[10px] font-bold tracking-wider bg-purple-100 text-purple-600 dark:bg-purple-900/30 dark:text-purple-400">
                                                        <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                                                            <path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20" />
                                                            <path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z" />
                                                        </svg>
                                                        {group.course_name}
                                                    </span>
                                                )}
                                                {group.is_private && (
                                                    <span className="px-2.5 py-0.5 rounded-full text-[10px] font-bold tracking-wider bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-400 uppercase flex items-center gap-1">
                                                        <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5"><rect x="3" y="11" width="18" height="11" rx="2" ry="2" /><path d="M7 11V7a5 5 0 0 1 10 0v4" /></svg>
                                                        Private
                                                    </span>
                                                )}
                                            </motion.div>
                                        )}
                                    </AnimatePresence>
                                </div>

                                {/* Close Button (from InstructionsModal style) */}
                                <div className="relative z-20 self-start">
                                    <motion.button
                                        onClick={onClose}
                                        whileHover={{ scale: 1.1 }}
                                        whileTap={{ scale: 0.95 }}
                                        className="flex-shrink-0 flex items-center justify-center rounded-lg sm:rounded-xl border border-zinc-200/80 bg-white/80 backdrop-blur-md p-2 text-zinc-500 shadow-sm transition-colors hover:bg-zinc-50 dark:border-zinc-700/80 dark:bg-zinc-800/80 dark:text-zinc-300 dark:hover:bg-zinc-700"
                                        aria-label="Close modal"
                                    >
                                        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" className="sm:w-5 sm:h-5">
                                            <line x1="18" y1="6" x2="6" y2="18"></line>
                                            <line x1="6" y1="6" x2="18" y2="18"></line>
                                        </svg>
                                    </motion.button>
                                </div>
                            </motion.div>
                        </motion.div>
                    </motion.div>

                        {/* Main Content Area: Side-by-side on Desktop, Stacked on Mobile */}
                        <div 
                            onScroll={handleScroll}
                            className="flex flex-col md:flex-row flex-1 overflow-y-auto md:overflow-hidden border-t border-slate-100 dark:border-slate-800/80 custom-scrollbar"
                        >
                            {/* Project Info & Resources (Left Side on Desktop) */}
                            <div 
                                onScroll={handleScroll}
                                className="md:w-1/2 p-4 sm:p-5 bg-slate-50 dark:bg-[#0f111a] border-b md:border-b-0 md:border-r border-slate-100 dark:border-slate-800/80 md:overflow-y-auto custom-scrollbar shrink-0"
                            >
                                {/* Stats Row */}
                                <div className="bg-zinc-50/50 dark:bg-zinc-900/30 border border-zinc-200/50 dark:border-zinc-800/80 rounded-[1.25rem] p-2 shadow-inner w-full mb-6">
                                    <div className="flex items-stretch justify-between">
                                        <div className="flex-1 bg-white dark:bg-slate-800/80 border border-slate-200/80 dark:border-slate-700/80 rounded-[0.85rem] p-3 shadow-sm flex flex-col items-center justify-center transition-all hover:shadow-md hover:border-blue-200 dark:hover:border-blue-800/60">
                                            <div className="text-[20px] sm:text-[24px] font-bold text-blue-600 dark:text-blue-400 leading-none mb-1">{group.member_count}</div>
                                            <div className="text-[10px] sm:text-[11px] font-bold text-slate-500 dark:text-slate-400 uppercase tracking-wider">Members</div>
                                        </div>
                                        
                                        <div className="flex items-center justify-center px-1.5 sm:px-2">
                                            <div className="w-[1px] h-[60%] bg-zinc-200 dark:bg-zinc-700/50" />
                                        </div>

                                        <div className="flex-1 bg-white dark:bg-slate-800/80 border border-slate-200/80 dark:border-slate-700/80 rounded-[0.85rem] p-3 shadow-sm flex flex-col items-center justify-center transition-all hover:shadow-md hover:border-emerald-200 dark:hover:border-emerald-800/60">
                                            <div className="text-[20px] sm:text-[24px] font-bold text-emerald-500 dark:text-emerald-400 leading-none mb-1">{group.online_count}</div>
                                            <div className="text-[10px] sm:text-[11px] font-bold text-slate-500 dark:text-slate-400 uppercase tracking-wider">Online</div>
                                        </div>

                                        <div className="flex items-center justify-center px-1.5 sm:px-2">
                                            <div className="w-[1px] h-[60%] bg-zinc-200 dark:bg-zinc-700/50" />
                                        </div>

                                        <div className="flex-1 bg-white dark:bg-slate-800/80 border border-slate-200/80 dark:border-slate-700/80 rounded-[0.85rem] p-3 shadow-sm flex flex-col items-center justify-center transition-all hover:shadow-md hover:border-slate-300 dark:hover:border-slate-600/60">
                                            <div className="text-[20px] sm:text-[24px] font-bold text-slate-800 dark:text-slate-200 leading-none mb-1">{group.max_members}</div>
                                            <div className="text-[10px] sm:text-[11px] font-bold text-slate-500 dark:text-slate-400 uppercase tracking-wider">Max</div>
                                        </div>
                                    </div>
                                </div>

                                <div className="mb-6">
                                    <h3 className="text-[11px] font-bold text-slate-500 dark:text-slate-400 mb-2.5 uppercase tracking-wider flex items-center gap-2">
                                        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" className="text-blue-500">
                                            <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline>
                                        </svg>
                                        Project Brief
                                    </h3>
                                    <div className="bg-zinc-50/50 dark:bg-zinc-900/30 border border-zinc-200/50 dark:border-zinc-800/80 rounded-[1.25rem] p-2 shadow-inner w-full">
                                        <div className="bg-white dark:bg-slate-800/80 p-4 sm:p-5 rounded-[16px] border border-slate-200/80 dark:border-slate-700/80 shadow-sm flex flex-col gap-3 group relative overflow-hidden transition-all hover:shadow-md hover:border-blue-200 dark:hover:border-blue-800/60">
                                            {/* Decorative background glow */}
                                            <div className="absolute top-0 right-0 w-32 h-32 bg-blue-500/5 rounded-full blur-2xl -translate-y-1/2 translate-x-1/2 pointer-events-none" />
                                            
                                            <div className="relative z-10">
                                                <div className="flex items-start justify-between gap-3 mb-1.5">
                                                    <h4 className="text-[15px] font-bold text-slate-900 dark:text-slate-100 leading-tight">Final Assignment: LMS Prototype</h4>
                                                    <span 
                                                        className="px-2.5 py-1 rounded-lg text-[10px] font-bold tracking-wide shrink-0 inline-flex uppercase"
                                                        style={{ background: `${categoryConfig.color}15`, color: categoryConfig.color }}
                                                    >
                                                        {categoryConfig.label}
                                                    </span>
                                                </div>
                                                <p className="text-[13px] text-slate-600 dark:text-slate-400 leading-relaxed">
                                                    Must include user authentication, role-based access, and a dynamic dashboard. Ensure responsive design.
                                                </p>
                                            </div>
                                            
                                            <div className="flex items-center gap-1.5 mt-1 pt-3 border-t border-slate-100 dark:border-slate-700/50 relative z-10">
                                                <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="text-rose-500">
                                                    <circle cx="12" cy="12" r="10"></circle><polyline points="12 6 12 12 16 14"></polyline>
                                                </svg>
                                                <span className="text-[11.5px] font-semibold text-rose-600 dark:text-rose-400">
                                                    Deadline: Friday, 11:59 PM
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                
                                <div className="mb-4">
                                    <h3 className="text-[11px] font-bold text-slate-500 dark:text-slate-400 mb-2.5 uppercase tracking-wider flex items-center gap-2">
                                        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" className="text-red-500">
                                            <path d="M13 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9z"></path><polyline points="13 2 13 9 20 9"></polyline>
                                        </svg>
                                        Teacher's Resources
                                    </h3>
                                    <div className="bg-zinc-50/50 dark:bg-zinc-900/30 border border-zinc-200/50 dark:border-zinc-800/80 rounded-[1.25rem] p-2 shadow-inner w-full flex flex-col gap-2">
                                        <div className="flex flex-col gap-2 relative">
                                            <Carousel 
                                                index={currentResourcePage} 
                                                onIndexChange={setCurrentResourcePage} 
                                                className="w-full"
                                            >
                                                <CarouselContent className="items-start">
                                                    {resourcePages.map((page, pageIndex) => (
                                                        <CarouselItem key={`page-${pageIndex}`}>
                                                            <div className="flex flex-col gap-2 w-full pb-1 min-h-[130px]">
                                                                {page.map((resource) => (
                                                                    <div key={resource.id} className="bg-white dark:bg-slate-800/80 p-3 rounded-[16px] border border-slate-200/80 dark:border-slate-700/80 shadow-sm flex items-center justify-between group cursor-pointer hover:shadow-md hover:border-red-200 dark:hover:border-red-800/60 transition-all">
                                                                        <div className="flex items-center gap-3.5">
                                                                            <div className="w-10 h-10 rounded-[10px] bg-red-50 text-red-500 border border-red-100 dark:bg-red-500/10 dark:text-red-400 dark:border-red-500/20 flex items-center justify-center shrink-0 group-hover:scale-105 transition-transform">
                                                                                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline></svg>
                                                                            </div>
                                                                            <div className="flex flex-col">
                                                                                <div className="text-[14px] font-bold text-slate-800 dark:text-slate-200 leading-tight mb-0.5">{resource.name}</div>
                                                                                <div className="text-[11.5px] font-medium text-slate-500 flex items-center gap-1.5 mt-0.5">
                                                                                    <span className="px-1.5 py-0.5 rounded-md bg-slate-100 dark:bg-slate-700/50 text-[10px] uppercase tracking-wide">{resource.type}</span>
                                                                                    <span>{resource.size}</span>
                                                                                </div>
                                                                            </div>
                                                                        </div>
                                                                        <motion.button
                                                                            type="button"
                                                                            disabled={downloadProgress[resource.id] !== undefined}
                                                                            onClick={(e) => handleDownloadResource(e, resource)}
                                                                            whileHover={downloadProgress[resource.id] === undefined ? { scale: 1.15 } : {}}
                                                                            whileTap={downloadProgress[resource.id] === undefined ? { scale: 0.9 } : {}}
                                                                            className="relative min-w-[36px] min-h-[36px] flex items-center justify-center shrink-0 rounded-full focus:outline-none disabled:cursor-default"
                                                                            aria-label={`Download ${resource.name}`}
                                                                        >
                                                                            <AnimatePresence>
                                                                                {(downloadProgress[resource.id] !== undefined || completedResources.includes(resource.id)) && (
                                                                                    <motion.div
                                                                                        initial={{ scale: 0, opacity: 0 }}
                                                                                        animate={{ scale: 1, opacity: 1 }}
                                                                                        exit={{ scale: 0, opacity: 0 }}
                                                                                        transition={{ type: "spring", stiffness: 400, damping: 20 }}
                                                                                        className={`absolute inset-0 rounded-full ${
                                                                                            downloadProgress[resource.id] !== undefined
                                                                                                ? 'bg-red-50 dark:bg-red-500/10'
                                                                                                : 'bg-red-100 dark:bg-red-900/40'
                                                                                        }`}
                                                                                    />
                                                                                )}
                                                                            </AnimatePresence>
                                                                            <div className="relative z-10 flex items-center justify-center w-full h-full">
                                                                                {(downloadProgress[resource.id] !== undefined || completedResources.includes(resource.id)) && (
                                                                                    <AnimatedCircularProgressBar
                                                                                        max={100}
                                                                                        min={0}
                                                                                        value={completedResources.includes(resource.id) ? 100 : downloadProgress[resource.id]!}
                                                                                        gaugePrimaryColor="#ef4444"
                                                                                        gaugeSecondaryColor="rgba(239, 68, 68, 0.2)"
                                                                                        className="absolute w-[40px] h-[40px] pointer-events-none"
                                                                                        hideText={true}
                                                                                    />
                                                                                )}

                                                                                {completedResources.includes(resource.id) ? (
                                                                                    <motion.svg
                                                                                        xmlns="http://www.w3.org/2000/svg"
                                                                                        viewBox="0 0 24 24"
                                                                                        fill="none"
                                                                                        stroke="currentColor"
                                                                                        className="w-4 h-4 text-red-500"
                                                                                        strokeWidth="3"
                                                                                        strokeLinecap="round"
                                                                                        strokeLinejoin="round"
                                                                                        initial={{ pathLength: 0, opacity: 0 }}
                                                                                        animate={{ pathLength: 1, opacity: 1 }}
                                                                                        transition={{ duration: 0.4, ease: "easeOut" }}
                                                                                    >
                                                                                        <motion.path d="M20 6 9 17l-5-5" />
                                                                                    </motion.svg>
                                                                                ) : (
                                                                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="text-red-500 dark:text-red-400">
                                                                                        <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
                                                                                        <polyline points="7 10 12 15 17 10" />
                                                                                        <line x1="12" x2="12" y1="15" y2="3" />
                                                                                    </svg>
                                                                                )}
                                                                            </div>
                                                                        </motion.button>
                                                                    </div>
                                                                ))}
                                                            </div>
                                                        </CarouselItem>
                                                    ))}
                                                </CarouselContent>
                                            </Carousel>
                                        </div>

                                        {/* Pagination Controls */}
                                        {totalResourcePages > 1 && (
                                            <div className="w-full pt-1.5 mt-1 relative z-10">
                                                <div className="flex items-center justify-between w-full gap-2 bg-white dark:bg-slate-900/50 p-1.5 rounded-[14px] border border-slate-200/60 dark:border-slate-700/50 shadow-sm transition-all duration-300 hover:shadow-md">
                                                    <button 
                                                        type="button"
                                                        onClick={() => setCurrentResourcePage(prev => Math.max(0, prev - 1))} 
                                                        disabled={currentResourcePage === 0}
                                                        className={`w-9 h-9 rounded-[10px] flex items-center justify-center transition-all shadow-sm cursor-pointer border ${
                                                            currentResourcePage === 0
                                                                ? 'bg-slate-50/50 dark:bg-slate-800/40 border-slate-100 dark:border-slate-700/40 text-slate-300 dark:text-slate-600 cursor-not-allowed'
                                                                : 'bg-white dark:bg-slate-800 border-slate-300 dark:border-slate-600 text-slate-500 hover:text-blue-600 hover:bg-slate-50/50 dark:hover:bg-slate-700/50 hover:border-blue-300 dark:hover:border-blue-500'
                                                        }`}
                                                    >
                                                        <svg className="w-4 h-4" fill="none" stroke="currentColor" strokeWidth="3" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" d="M15 19l-7-7 7-7" /></svg>
                                                    </button>
                                                    <span className="text-[13px] font-bold text-slate-700 dark:text-slate-300 text-center tracking-wide flex-1">
                                                        Page {currentResourcePage + 1} <span className="text-slate-400 dark:text-slate-500 font-medium mx-0.5">/</span> {totalResourcePages}
                                                    </span>
                                                    <button 
                                                        type="button"
                                                        onClick={() => setCurrentResourcePage(prev => Math.min(totalResourcePages - 1, prev + 1))} 
                                                        disabled={currentResourcePage === totalResourcePages - 1}
                                                        className={`w-9 h-9 rounded-[10px] flex items-center justify-center transition-all shadow-sm cursor-pointer border ${
                                                            currentResourcePage === totalResourcePages - 1
                                                                ? 'bg-slate-50/50 dark:bg-slate-800/40 border-slate-100 dark:border-slate-700/40 text-slate-300 dark:text-slate-600 cursor-not-allowed'
                                                                : 'bg-white dark:bg-slate-800 border-slate-300 dark:border-slate-600 text-slate-500 hover:text-blue-600 hover:bg-slate-50/50 dark:hover:bg-slate-700/50 hover:border-blue-300 dark:hover:border-blue-500'
                                                        }`}
                                                    >
                                                        <svg className="w-4 h-4" fill="none" stroke="currentColor" strokeWidth="3" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" d="M9 5l7 7-7 7" /></svg>
                                                    </button>
                                                </div>
                                            </div>
                                        )}
                                    </div>
                                </div>
                            </div>

                            {/* Members List (Right Side on Desktop) */}
                            <div 
                                onScroll={handleScroll}
                                className="flex-1 md:w-1/2 md:overflow-auto p-4 sm:p-5 bg-white dark:bg-slate-900 custom-scrollbar shrink-0"
                                style={{ 
                                    scrollBehavior: 'smooth',
                                    // @ts-ignore
                                    WebkitOverflowScrolling: 'touch'
                                }}
                            >
                                <div className="flex items-center justify-between mb-4">
                                    <h3 className="m-0 text-[14px] font-bold text-slate-700 dark:text-slate-300">
                                        Members
                                    </h3>
                                    <span className="text-[12px] font-medium text-slate-500 dark:text-slate-400 bg-slate-100 dark:bg-slate-800/60 px-2 py-0.5 rounded-md">
                                        {group.member_count} / {group.max_members}
                                    </span>
                                </div>
                                <div className="bg-zinc-50/50 dark:bg-zinc-900/30 border border-zinc-200/50 dark:border-zinc-800/80 rounded-[1.25rem] p-1 shadow-inner w-full">
                                    <div className="flex flex-col gap-2 max-h-[260px] md:max-h-[300px] overflow-y-auto custom-scrollbar p-1.5">
                                        {Array.from(new Map(group.members.map(m => [m.user_id, m])).values()).map((member, index) => {
                                            const roleInfo = getRoleInfo(member.role);
                                            const isOwner = member.role === 'owner';
                                            const isMe = member.user_email === myProfile.email || member.user_name.toLowerCase().includes('deasis');
                                            
                                            const themeColor = isOwner ? '#f59e0b' : '#3b82f6';
                                            
                                            const nameSum = member.user_name.split('').reduce((sum, char) => sum + char.charCodeAt(0), 0);
                                            const userLevel = isMe ? myLevel : ((nameSum % 10) + 1);
                                            const userProgress = isMe ? myProgress : ((nameSum % 80) + 10);
                                            const userAvatar = isMe && myImages.profileImage ? myImages.profileImage : member.user_avatar;
                                            return (
                                                <motion.div
                                                    key={member.id}
                                                    initial={{ opacity: 0, x: -10 }}
                                                    animate={{ opacity: 1, x: 0 }}
                                                    transition={{ delay: index * 0.03 }}
                                                    className="flex items-center gap-3 p-3 rounded-[16px] bg-white dark:bg-slate-800/80 border border-slate-200/80 dark:border-slate-700/80 shadow-sm transition-all duration-300 group/member hover:shadow-md hover:border-slate-300 dark:hover:border-slate-600"
                                                >
                                                    <div className="relative flex-shrink-0 group-hover/member:scale-105 transition-transform duration-300">
                                                        <AnimatedCircularProgressBar
                                                            max={100}
                                                            min={0}
                                                            value={userProgress}
                                                            gaugePrimaryColor={userLevel >= 15 ? '#eab308' : userLevel >= 10 ? '#cbd5e1' : themeColor}
                                                            gaugeSecondaryColor={isDarkMode ? `${themeColor}25` : `${themeColor}40`}
                                                            className="w-11 h-11"
                                                        >
                                                            <div className="absolute inset-1.5 rounded-full flex items-center justify-center shadow-sm overflow-hidden z-10" style={{ backgroundColor: `${themeColor}15` }}>
                                                                {userAvatar ? (
                                                                    <img src={userAvatar} alt={member.user_name} className="w-full h-full object-cover" />
                                                                ) : (
                                                                    <span className="text-[12px] font-bold leading-none" style={{ color: themeColor }}>
                                                                        {member.user_name.split(' ').map(n => n[0]).join('').substring(0, 2).toUpperCase()}
                                                                    </span>
                                                                )}
                                                            </div>

                                                            <div className={`absolute -bottom-0.5 left-1/2 -translate-x-1/2 min-w-[28px] h-[14px] px-1 rounded-md flex items-center justify-center text-[8px] font-bold tracking-wider shadow-sm border-[2px] z-20 transition-colors duration-300 ${userLevel >= 15 ? 'text-blue-800' : 'text-white'} ${isDarkMode ? (member.is_online ? 'border-emerald-400' : 'border-slate-800/40') : (member.is_online ? 'border-emerald-500' : 'border-white')}`} style={{ backgroundColor: userLevel >= 15 ? '#eab308' : themeColor }}>
                                                                <span className="ml-[0.05em]">{userLevel >= 20 ? 'MAX' : `LV.${userLevel}`}</span>
                                                            </div>
                                                        </AnimatedCircularProgressBar>
                                                    </div>
                                                    <div className="flex-1 min-w-0">
                                                        <div className="text-[14px] font-bold text-slate-800 dark:text-slate-200">
                                                            {member.user_name}
                                                        </div>
                                                        <div className="text-[12px] font-medium text-slate-500 dark:text-slate-400">
                                                            {member.is_online ? 'Online' : formatLastActive(member.last_active)}
                                                        </div>
                                                    </div>
                                                    <span 
                                                        className="px-2.5 py-1 rounded-[8px] text-[10px] font-bold tracking-wide flex-shrink-0"
                                                        style={{ background: `${themeColor}15`, color: themeColor }}
                                                    >
                                                        {roleInfo.label}
                                                    </span>
                                                </motion.div>
                                            );
                                        })}
                                    </div>
                                </div>
                            </div>
                        </div>

                        {/* Footer Actions (SaaS solid filled buttons, equal width) */}
                        <div className="p-4 sm:p-5 border-t border-slate-100 dark:border-slate-800/80 bg-white dark:bg-slate-900 flex flex-col sm:flex-row gap-2.5 sm:gap-3">
                            {group.is_member ? (
                                <>
                                    <motion.button
                                        whileHover={{ scale: 1.02 }} 
                                        whileTap={{ scale: 0.98 }}
                                        onClick={() => { onLeave(group.id); onClose(); }}
                                        className="flex-1 py-3 px-4 text-[13px] font-bold rounded-[14px] transition-colors shadow-sm flex items-center justify-center gap-1.5 focus:outline-none bg-red-100 hover:bg-red-200 dark:bg-red-950/40 dark:hover:bg-red-900/60 text-red-700 dark:text-red-300 border-none cursor-pointer"
                                    >
                                        Leave Group
                                    </motion.button>
                                    <motion.button
                                        whileHover={{ scale: 1.02 }}
                                        whileTap={{ scale: 0.98 }}
                                        onClick={() => { window.open('https://discord.com', '_blank'); onClose(); }}
                                        className="flex-1 py-3 px-4 text-[13px] font-bold rounded-[14px] transition-colors shadow-sm flex items-center justify-center gap-2 focus:outline-none bg-[#5865F2] hover:bg-[#4752C4] text-white border-none cursor-pointer"
                                    >
                                        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                                            <path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"></path>
                                        </svg>
                                        Open Discord Server
                                    </motion.button>
                                </>
                            ) : (
                                <motion.button
                                    whileHover={{ scale: 1.02 }}
                                    whileTap={{ scale: 0.98 }}
                                    onClick={() => { onJoin(group.id); onClose(); }}
                                    className="flex-1 py-3 px-4 text-[13px] font-bold rounded-[14px] transition-colors shadow-sm flex items-center justify-center gap-2 focus:outline-none bg-emerald-100 hover:bg-emerald-200 dark:bg-emerald-900/50 dark:hover:bg-emerald-900/70 text-emerald-700 dark:text-emerald-300 border-none cursor-pointer"
                                >
                                    <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                                        <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
                                        <circle cx="9" cy="7" r="4" />
                                        <line x1="19" y1="8" x2="19" y2="14" />
                                        <line x1="22" y1="11" x2="16" y2="11" />
                                    </svg>
                                    Join Group
                                </motion.button>
                            )}
                        </div>
                    </motion.div>
                </div>
            )}
        </AnimatePresence>,
        document.body
    );
};

export default GroupDetailModal;
