/**
 * DOCX Export Utilities
 * Provides client-side DOCX export for tool outputs
 * Uses docx library for professional document generation
 */

import { Document, Paragraph, TextRun, HeadingLevel, AlignmentType, Packer } from 'docx';

interface DocxExportOptions {
  title?: string;
  subtitle?: string;
  content: string;
  metadata?: {
    author?: string;
    subject?: string;
    createdAt?: Date;
  };
}

/**
 * Export text content to DOCX format
 */
export const exportToDocx = async (options: DocxExportOptions): Promise<Blob> => {
  const { title, subtitle, content, metadata } = options;
  
  // Split content into paragraphs
  const paragraphs = content.split('\n\n').filter(p => p.trim());
  
  const doc = new Document({
    sections: [{
      properties: {
        page: {
          margin: {
            top: 1440, // 1 inch in twips
            right: 1440,
            bottom: 1440,
            left: 1440,
          },
        },
      },
      children: [
        // Title
        ...(title ? [new Paragraph({
          text: title,
          heading: HeadingLevel.TITLE,
          alignment: AlignmentType.CENTER,
          spacing: { after: 240 },
        })] : []),
        
        // Subtitle
        ...(subtitle ? [new Paragraph({
          text: subtitle,
          alignment: AlignmentType.CENTER,
          spacing: { after: 400 },
        })] : []),
        
        // Content paragraphs
        ...paragraphs.map((text, index) => new Paragraph({
          children: [
            new TextRun({
              text: text.trim(),
              size: 24, // 12pt
            }),
          ],
          spacing: { after: index < paragraphs.length - 1 ? 200 : 0 },
          alignment: AlignmentType.JUSTIFIED,
        })),
        
        // Footer with metadata
        ...(metadata ? [new Paragraph({
          children: [
            new TextRun({
              text: `Generated by STI eLMS Student Tools${metadata.createdAt ? ` on ${metadata.createdAt.toLocaleDateString()}` : ''}`,
              size: 18,
              color: '999999',
              italics: true,
            }),
          ],
          alignment: AlignmentType.CENTER,
          spacing: { before: 400 },
        })] : []),
      ],
    }],
  });
  
  return await Packer.toBlob(doc);
};

/**
 * Export bibliography/references to DOCX
 */
export const exportBibliographyToDocx = async (
  references: Array<{
    citation: string;
    format: string;
  }>,
  options?: {
    title?: string;
    style?: 'APA' | 'MLA' | 'Chicago';
  }
): Promise<Blob> => {
  const { title = 'Bibliography', style = 'APA' } = options || {};
  
  const doc = new Document({
    sections: [{
      properties: {
        page: {
          margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 },
        },
      },
      children: [
        // Title
        new Paragraph({
          text: title,
          heading: HeadingLevel.HEADING_1,
          alignment: AlignmentType.CENTER,
          spacing: { after: 400 },
        }),
        
        // Style indicator
        new Paragraph({
          text: `${style} Format`,
          alignment: AlignmentType.CENTER,
          spacing: { after: 400 },
        }),
        
        // References with hanging indent
        ...references.map((ref, index) => new Paragraph({
          children: [
            new TextRun({
              text: `${index + 1}. ${ref.citation}`,
              size: 22,
            }),
          ],
          spacing: { after: 200 },
          alignment: AlignmentType.LEFT,
          indent: { left: 720, hanging: 720 }, // Hanging indent for citations
        })),
        
        // Footer
        new Paragraph({
          children: [
            new TextRun({
              text: `Generated by STI eLMS Reference Manager`,
              size: 18,
              color: '999999',
              italics: true,
            }),
          ],
          alignment: AlignmentType.CENTER,
          spacing: { before: 400 },
        }),
      ],
    }],
  });
  
  return await Packer.toBlob(doc);
};

/**
 * Download blob as file
 */
export const downloadBlob = (blob: Blob, filename: string): void => {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};

/**
 * Tool-specific export helpers
 */
/**
 * Export paraphrased text to DOCX
 */
export const exportParaphraseToDocx = async (original: string, paraphrased: string, mode: string): Promise<void> => {
  const blob = await exportToDocx({
    title: 'Paraphrased Text',
    subtitle: `Mode: ${mode.charAt(0).toUpperCase() + mode.slice(1)}`,
    content: `Original:\n\n${original}\n\n---\n\nParaphrased:\n\n${paraphrased}`,
    metadata: {
      author: 'STI eLMS Paraphraser',
      createdAt: new Date(),
    },
  });
  
  downloadBlob(blob, `paraphrased_${mode}_${new Date().toISOString().split('T')[0]}.docx`);
};

export const exportSummaryToDocx = async (original: string, summary: string, format: string): Promise<void> => {
  const blob = await exportToDocx({
    title: 'Text Summary',
    subtitle: `Format: ${format}`,
    content: `Summary:\n\n${summary}\n\n---\n\nOriginal Text:\n\n${original}`,
    metadata: {
      author: 'STI eLMS Text Summarizer',
      createdAt: new Date(),
    },
  });
  
  downloadBlob(blob, `summary_${format.toLowerCase().replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.docx`);
};

export const exportGrammarCheckToDocx = async (text: string, corrections: string[]): Promise<void> => {
  const blob = await exportToDocx({
    title: 'Grammar Check Results',
    content: `Corrected Text:\n\n${text}\n\n---\n\nCorrections Made:\n${corrections.map((c, i) => `${i + 1}. ${c}`).join('\n')}`,
    metadata: {
      author: 'STI eLMS Grammar Checker',
      createdAt: new Date(),
    },
  });
  
  downloadBlob(blob, `grammar_check_${new Date().toISOString().split('T')[0]}.docx`);
};
