/**
 * TXT Export Utilities
 * Simple text file exports for tool outputs
 */

interface TxtExportOptions {
  content: string;
  header?: string;
  footer?: string;
}

/**
 * Export text content to TXT format
 */
export const exportToTxt = (options: TxtExportOptions): Blob => {
  const { content, header, footer } = options;
  
  let textContent = '';
  
  if (header) {
    textContent += `${header}\n${'='.repeat(header.length)}\n\n`;
  }
  
  textContent += content;
  
  if (footer) {
    textContent += `\n\n${'-'.repeat(40)}\n${footer}`;
  }
  
  return new Blob([textContent], { type: 'text/plain;charset=utf-8' });
};

/**
 * Download blob as .txt file
 */
export const downloadTxt = (blob: Blob, filename: string): void => {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename.endsWith('.txt') ? filename : `${filename}.txt`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};

/**
 * Tool-specific TXT exports
 */
export const exportParaphraseToTxt = (original: string, paraphrased: string, mode: string): void => {
  const content = `PARAPHRASED TEXT
Mode: ${mode.toUpperCase()}
Date: ${new Date().toLocaleString()}

--- ORIGINAL ---

${original}

--- PARAPHRASED ---

${paraphrased}

---
Generated by STI eLMS Paraphraser`;
  
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  downloadTxt(blob, `paraphrased_${mode}_${new Date().toISOString().split('T')[0]}`);
};

export const exportSummaryToTxt = (original: string, summary: string, format: string): void => {
  const content = `TEXT SUMMARY
Format: ${format}
Date: ${new Date().toLocaleString()}

--- SUMMARY ---

${summary}

--- ORIGINAL ---

${original}

---
Generated by STI eLMS Text Summarizer`;
  
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  downloadTxt(blob, `summary_${format.toLowerCase().replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}`);
};

export const exportGrammarCheckToTxt = (text: string, corrections: string[]): void => {
  const content = `GRAMMAR CHECK RESULTS
Date: ${new Date().toLocaleString()}

--- CORRECTED TEXT ---

${text}

--- CORRECTIONS ---
${corrections.map((c, i) => `${i + 1}. ${c}`).join('\n')}

---
Generated by STI eLMS Grammar Checker`;
  
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  downloadTxt(blob, `grammar_check_${new Date().toISOString().split('T')[0]}`);
};

export const exportBibliographyToTxt = (references: Array<{ citation: string; format: string }>, style: string): void => {
  const content = `BIBLIOGRAPHY
Style: ${style}
Date: ${new Date().toLocaleString()}

${references.map((ref, i) => `[${i + 1}] ${ref.citation}`).join('\n\n')}

---
Generated by STI eLMS Reference Manager`;
  
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  downloadTxt(blob, `bibliography_${style.toLowerCase()}_${new Date().toISOString().split('T')[0]}`);
};
