/**
 * Export Utilities
 * Provides PDF and Excel export functionality for grades and reports
 */

import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';

// ============================================
// TYPES
// ============================================
export interface GradeExportData {
    studentName: string;
    studentId: string;
    section: string;
    course: string;
    assignments: {
        title: string;
        score: number;
        maxScore: number;
        percentage: number;
        status: string;
        submittedAt: string;
    }[];
    averageGrade: number;
    totalPoints: number;
    maxPoints: number;
}

export interface ClassGradesSummary {
    courseName: string;
    courseCode: string;
    section: string;
    semester: string;
    teacherName: string;
    exportDate: string;
    students: {
        rank: number;
        name: string;
        studentId: string;
        assignments: number[];
        average: number;
        grade: string;
        remarks: string;
    }[];
    assignmentTitles: string[];
}

// ============================================
// HELPER FUNCTIONS
// ============================================
const getLetterGrade = (percentage: number): string => {
    if (percentage >= 97) return 'A+';
    if (percentage >= 93) return 'A';
    if (percentage >= 90) return 'A-';
    if (percentage >= 87) return 'B+';
    if (percentage >= 83) return 'B';
    if (percentage >= 80) return 'B-';
    if (percentage >= 77) return 'C+';
    if (percentage >= 73) return 'C';
    if (percentage >= 70) return 'C-';
    if (percentage >= 67) return 'D+';
    if (percentage >= 63) return 'D';
    if (percentage >= 60) return 'D-';
    return 'F';
};

const getRemarks = (percentage: number): string => {
    if (percentage >= 75) return 'PASSED';
    return 'FAILED';
};

// ============================================
// PDF EXPORT
// ============================================

/**
 * Export class grades to PDF
 */
export const exportGradesToPDF = (data: ClassGradesSummary): void => {
    const doc = new jsPDF('landscape', 'mm', 'a4');
    const pageWidth = doc.internal.pageSize.getWidth();
    
    // Header
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text('GRADE REPORT', pageWidth / 2, 15, { align: 'center' });
    
    doc.setFontSize(14);
    doc.text(`${data.courseName} (${data.courseCode})`, pageWidth / 2, 23, { align: 'center' });
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Section: ${data.section}`, 14, 33);
    doc.text(`Semester: ${data.semester}`, 14, 38);
    doc.text(`Instructor: ${data.teacherName}`, 14, 43);
    doc.text(`Date Generated: ${data.exportDate}`, pageWidth - 14, 33, { align: 'right' });
    
    // Build table headers
    const headers = ['Rank', 'Student Name', 'Student ID', ...data.assignmentTitles, 'Average', 'Grade', 'Remarks'];
    
    // Build table body
    const body = data.students.map(student => [
        student.rank.toString(),
        student.name,
        student.studentId,
        ...student.assignments.map(score => score.toFixed(1)),
        student.average.toFixed(2),
        student.grade,
        student.remarks,
    ]);
    
    // Generate table
    autoTable(doc, {
        head: [headers],
        body: body,
        startY: 50,
        theme: 'grid',
        styles: {
            fontSize: 8,
            cellPadding: 2,
        },
        headStyles: {
            fillColor: [59, 130, 246], // Blue
            textColor: 255,
            fontStyle: 'bold',
        },
        alternateRowStyles: {
            fillColor: [248, 250, 252],
        },
        columnStyles: {
            0: { halign: 'center', cellWidth: 12 }, // Rank
            1: { cellWidth: 40 }, // Name
            2: { cellWidth: 25 }, // ID
        },
    });
    
    // Footer
    const finalY = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY || 200;
    doc.setFontSize(8);
    doc.setTextColor(100);
    doc.text('This is a computer-generated document. No signature required.', pageWidth / 2, finalY + 10, { align: 'center' });
    doc.text(`Generated by eLMS Teacher Portal - ${new Date().toLocaleString()}`, pageWidth / 2, finalY + 15, { align: 'center' });
    
    // Save
    doc.save(`Grade_Report_${data.courseCode}_${data.section}_${new Date().toISOString().split('T')[0]}.pdf`);
};

/**
 * Export individual student report to PDF
 */
export const exportStudentReportPDF = (data: GradeExportData): void => {
    const doc = new jsPDF('portrait', 'mm', 'a4');
    const pageWidth = doc.internal.pageSize.getWidth();
    
    // Header
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text('STUDENT GRADE REPORT', pageWidth / 2, 20, { align: 'center' });
    
    // Student Info
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text(`Student: ${data.studentName}`, 14, 35);
    doc.text(`Student ID: ${data.studentId}`, 14, 42);
    doc.text(`Section: ${data.section}`, 14, 49);
    doc.text(`Course: ${data.course}`, 14, 56);
    
    // Summary Box
    doc.setFillColor(248, 250, 252);
    doc.roundedRect(pageWidth - 80, 30, 66, 30, 3, 3, 'F');
    doc.setFontSize(10);
    doc.text('Overall Grade', pageWidth - 47, 38, { align: 'center' });
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(59, 130, 246);
    doc.text(`${data.averageGrade.toFixed(1)}%`, pageWidth - 47, 52, { align: 'center' });
    doc.setTextColor(0);
    
    // Assignments Table
    const headers = ['Assignment', 'Score', 'Max', '%', 'Status', 'Submitted'];
    const body = data.assignments.map(a => [
        a.title,
        a.score.toString(),
        a.maxScore.toString(),
        `${a.percentage.toFixed(1)}%`,
        a.status,
        a.submittedAt,
    ]);
    
    autoTable(doc, {
        head: [headers],
        body: body,
        startY: 70,
        theme: 'striped',
        styles: { fontSize: 9 },
        headStyles: {
            fillColor: [59, 130, 246],
            textColor: 255,
        },
    });
    
    // Save
    doc.save(`Student_Report_${data.studentName.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.pdf`);
};

// ============================================
// EXCEL EXPORT
// ============================================

/**
 * Export class grades to Excel
 */
export const exportGradesToExcel = (data: ClassGradesSummary): void => {
    // Create workbook
    const wb = XLSX.utils.book_new();
    
    // Header info
    const headerData = [
        ['GRADE REPORT'],
        [`${data.courseName} (${data.courseCode})`],
        [],
        ['Section:', data.section],
        ['Semester:', data.semester],
        ['Instructor:', data.teacherName],
        ['Date Generated:', data.exportDate],
        [],
    ];
    
    // Table headers
    const tableHeaders = ['Rank', 'Student Name', 'Student ID', ...data.assignmentTitles, 'Average', 'Grade', 'Remarks'];
    
    // Table data
    const tableData = data.students.map(student => [
        student.rank,
        student.name,
        student.studentId,
        ...student.assignments,
        student.average,
        student.grade,
        student.remarks,
    ]);
    
    // Combine all data
    const wsData = [...headerData, tableHeaders, ...tableData];
    
    // Create worksheet
    const ws = XLSX.utils.aoa_to_sheet(wsData);
    
    // Set column widths
    ws['!cols'] = [
        { wch: 6 },  // Rank
        { wch: 25 }, // Name
        { wch: 15 }, // ID
        ...data.assignmentTitles.map(() => ({ wch: 10 })),
        { wch: 10 }, // Average
        { wch: 8 },  // Grade
        { wch: 10 }, // Remarks
    ];
    
    // Add worksheet to workbook
    XLSX.utils.book_append_sheet(wb, ws, 'Grades');
    
    // Save
    XLSX.writeFile(wb, `Grade_Report_${data.courseCode}_${data.section}_${new Date().toISOString().split('T')[0]}.xlsx`);
};

/**
 * Export attendance to Excel
 */
export const exportAttendanceToExcel = (data: {
    courseName: string;
    section: string;
    dates: string[];
    students: {
        name: string;
        studentId: string;
        attendance: ('P' | 'A' | 'L' | 'E')[]; // Present, Absent, Late, Excused
        totalPresent: number;
        totalAbsent: number;
        attendanceRate: number;
    }[];
}): void => {
    const wb = XLSX.utils.book_new();
    
    const headerData = [
        ['ATTENDANCE REPORT'],
        [`${data.courseName} - ${data.section}`],
        [],
        ['Legend: P = Present, A = Absent, L = Late, E = Excused'],
        [],
    ];
    
    const tableHeaders = ['Student Name', 'Student ID', ...data.dates, 'Present', 'Absent', 'Rate'];
    
    const tableData = data.students.map(student => [
        student.name,
        student.studentId,
        ...student.attendance,
        student.totalPresent,
        student.totalAbsent,
        `${student.attendanceRate.toFixed(1)}%`,
    ]);
    
    const wsData = [...headerData, tableHeaders, ...tableData];
    const ws = XLSX.utils.aoa_to_sheet(wsData);
    
    XLSX.utils.book_append_sheet(wb, ws, 'Attendance');
    XLSX.writeFile(wb, `Attendance_${data.section}_${new Date().toISOString().split('T')[0]}.xlsx`);
};

// ============================================
// QUICK EXPORT FUNCTIONS
// ============================================

/**
 * Quick export - fetches data and exports in one call
 */
export const quickExportClassGrades = async (
    _courseCode: string,
    _section: string,
    format: 'pdf' | 'excel',
    fetchGradesFunction: () => Promise<ClassGradesSummary>
): Promise<void> => {
    try {
        const data = await fetchGradesFunction();
        
        if (format === 'pdf') {
            exportGradesToPDF(data);
        } else {
            exportGradesToExcel(data);
        }
    } catch (error) {
        console.error('Export failed:', error);
        throw error;
    }
};

export { getLetterGrade, getRemarks };
